package com.perfmonitor.report

import java.io.File
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter

object ReportWriter {

    private val fileTimeFmt    = DateTimeFormatter.ofPattern("yyyy-MM-dd_HH-mm-ss")
    private val displayTimeFmt = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")

    /**
     * Writes the full sequential analysis to
     * <projectRoot>/.perf-monitor/reports/<monitor>_<timestamp>.md
     *
     * Returns the file that was written.
     */
    fun write(
        projectBasePath: String,
        monitorName: String,
        packageName: String,
        sessionMode: String,
        foregroundScreen: String,
        capturedData: String,
        fileResults: Map<String, String>,   // fileName → per-file analysis
        finalSummary: String,
        selectedFileNames: List<String>
    ): File {
        val now       = LocalDateTime.now()
        val timestamp = now.format(fileTimeFmt)
        val display   = now.format(displayTimeFmt)

        val reportsDir = File("$projectBasePath/perf-monitor/reports").also { it.mkdirs() }
        val reportFile = File(reportsDir, "${monitorName.lowercase().replace(" / ", "_")}_$timestamp.md")

        reportFile.writeText(buildMarkdown(
            monitorName      = monitorName,
            packageName      = packageName,
            sessionMode      = sessionMode,
            foregroundScreen = foregroundScreen,
            capturedData     = capturedData,
            fileResults      = fileResults,
            finalSummary     = finalSummary,
            selectedFiles    = selectedFileNames,
            timestamp        = display
        ))

        return reportFile
    }

    private fun buildMarkdown(
        monitorName: String,
        packageName: String,
        sessionMode: String,
        foregroundScreen: String,
        capturedData: String,
        fileResults: Map<String, String>,
        finalSummary: String,
        selectedFiles: List<String>,
        timestamp: String
    ): String {
        val sb = StringBuilder()

        // ── Header ────────────────────────────────────────────────────
        sb.appendLine("# 📊 $monitorName Performance Report")
        sb.appendLine()
        sb.appendLine("| Field | Value |")
        sb.appendLine("|-------|-------|")
        sb.appendLine("| **App** | `$packageName` |")
        sb.appendLine("| **Monitor** | $monitorName |")
        sb.appendLine("| **Session** | $sessionMode |")
        if (foregroundScreen.isNotBlank())
            sb.appendLine("| **Foreground Screen** | `$foregroundScreen` |")
        sb.appendLine("| **Generated** | $timestamp |")
        sb.appendLine("| **Files Analysed** | ${if (fileResults.isEmpty()) "none (data-only)" else fileResults.size.toString()} |")
        sb.appendLine()

        // ── Files analysed list ───────────────────────────────────────
        if (selectedFiles.isNotEmpty()) {
            sb.appendLine("## 📁 Source Files Analysed")
            sb.appendLine()
            selectedFiles.forEach { sb.appendLine("- `$it`") }
            sb.appendLine()
        }

        // ── Raw captured data ─────────────────────────────────────────
        sb.appendLine("## 📡 Captured Performance Data")
        sb.appendLine()
        sb.appendLine("```")
        sb.appendLine(capturedData.take(4000))
        if (capturedData.length > 4000) sb.appendLine("... (truncated)")
        sb.appendLine("```")
        sb.appendLine()

        // ── Per-file analysis sections ────────────────────────────────
        if (fileResults.isNotEmpty()) {
            sb.appendLine("---")
            sb.appendLine()
            sb.appendLine("## 🔍 Per-File Analysis")
            sb.appendLine()

            fileResults.entries.forEachIndexed { idx, (fileName, analysis) ->
                sb.appendLine("### ${idx + 1}. `$fileName`")
                sb.appendLine()
                // Clean up any leftover prompt artefacts before writing
                sb.appendLine(analysis.trim())
                sb.appendLine()
                sb.appendLine("---")
                sb.appendLine()
            }
        }

        // ── Final summary ─────────────────────────────────────────────
        sb.appendLine("## 📋 Final Summary & Action Plan")
        sb.appendLine()
        sb.appendLine(finalSummary.trim())
        sb.appendLine()

        // ── Footer ────────────────────────────────────────────────────
        sb.appendLine("---")
        sb.appendLine()
        sb.appendLine("*Generated by Perf Monitor plugin · $timestamp*")

        return sb.toString()
    }
}